version: "3.8"

services:
  app:
    build:
      context: .
      target: base
    container_name: kantox_live_web
    command: mix phx.server
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - .:/kantox_live
